### PR TITLE
Fix wrong operator(should use / instead of *) on scaling factor, tested on Windows

### PR DESCRIPTION
**Pull request by Originalimoc**

### CODE REVIEW

**Comment by nashaofu** [comment]
The reason for this issue is here. I have already released a new version and it should have been fixed.
https://github.com/nashaofu/display-info/commit/f80e78bd571fa6cec5f96395278c3bb6f5765f85#diff-ee9da70e8a36920d0c024abb7c25308cb435c3dcba46a3566abca2a11fd1cfffR119

**Comment by Originalimoc** [comment]
Okay reverted that change, remaining is still desirable to merge

**Review by nashaofu — APPROVED** [review]

**Comment by nashaofu** [comment]
> Okay reverted that change, remaining is still desirable to merge

CI failed

**Review by nashaofu — CHANGES_REQUESTED** [review]
CI failed

**Comment by Originalimoc** [comment]
I didn't use rustfmt, try again?

**Review by nashaofu — APPROVED** [review]

**Comment by nashaofu** [comment]
> I didn't use rustfmt, try again?

If interested, you can participate in the development of the window screenshot function together https://github.com/nashaofu/screenshots-rs/pull/91

**Pull request merged**
